---
# tasks file for sample-apache
- name: enable httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: enable firewall
  service:
    name: firewalld
    state: started 
    enabled: true

- name: firewall http service
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes

- name: index
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - restart
