---
- name: hosts
  hosts: all
  tasks:
  
  - name: create partition
    parted:
      device: /dev/sdb
      number: 1
      flags: [lvm]
      state: present

  - name: create vg
    lvg:
      vg: vg0
      pvs: /dev/sdb1
    when: ansible_devices.sdb.partitions.sdb1 is defined

  - name: create logical volume
    lvol:
       vg: vg0
       lv: lv0
       size: 1500m
    when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float) > 1.5)

  - name: send message if volume grop not large enough
    debug:
      msg: Not enough space for logical volume  
    when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float) < 1.5)

  - name: create a smaller logical volume
    lvol:
      vg: vg0
      lv: lv0
      size: 1500m
    when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float) < 1.5)

  - name: create fs
    filesystem:
      dev: /dev/vg0/lv0
      fstype: xfs
    when: ansible_lvm.vgs.vg0 is defined


