---
- name: rolesplay
  hosts: all
  vars:
    haproxy_backend_servers:
    - name: web1
      address: 10.0.2.24
    - name: web2
      address: 10.0.2.25
  tasks:
    - name: role1
      include_role:
        name: haproxy-role
      when: ('proxy' in group_names)
    - name: role2
      include_role:
        name: php-role
      when: ('prod' in group_names)
